apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedirector
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kubedirector
  template:
    metadata:
      labels:
        name: kubedirector
    spec:
      serviceAccountName: kubedirector
      containers:
        - name: kubedirector
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - kubedirector
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kubedirector"
