apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kubedirectorapps.kubedirector.bluedata.io
spec:
  group: kubedirector.bluedata.io
  names:
    kind: KubeDirectorApp
    listKind: KubeDirectorAppList
    plural: kubedirectorapps
    singular: kubedirectorapp
  scope: Namespaced
  version: v1alpha1
  validation:
    openAPIV3Schema:
      properties:
        spec:
          required: [label, distro_id, version, roles, config, config_package, config_schema_version]
          properties:
            label:
              required: [name]
              properties:
                name:
                  type: string
                  minLength: 1
                description:
                  type: string
            distro_id:
              type: string
              minLength: 1
            version:
              type: string
              minLength: 1
            config_schema_version:
              type: integer
              minimum: 7
            image_repo_tag:
              type: string
              minLength: 1
            config_package:
              required: [package_url]
              properties:
                package_url:
                  type: string
                  pattern: '^(file|http)s?://.+\.tgz$'
            services:
              type: array
              items:
                required: [id]
                properties:
                  id:
                    type: string
                    minLength: 1
                    maxLength: 15
                    pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
                  label:
                    required: [name]
                    properties:
                      name:
                        type: string
                        minLength: 1
                      description:
                        type: string
                  endpoint:
                    required: [port]
                    properties:
                      port:
                        type: integer
                        minimum: 1
                        maximum: 65535
                      url_scheme:
                        type: string
                        minLength: 1
                      path:
                        type: string
                      is_dashboard:
                        type: boolean
            roles:
              type: array
              items:
                required: [id, cardinality]
                properties:
                  id:
                    type: string
                    minLength: 1
                  cardinality:
                    type: string
                    pattern: '^\d+\+?$'
                  image_repo_tag:
                    type: string
                    minLength: 1
                  config_package:
                    properties:
                      package_url:
                        type: string
                        pattern: '^(file|http)s?://.+\.tgz$'
                  persist_dirs:
                    type: array
                    items:
                      type: string
                      pattern: '^/.*[^/]$'
            config:
              required: [selected_roles, role_services]
              properties:
                config_meta:
                  type: object
                selected_roles:
                  type: array
                  items:
                    type: string
                    minLength: 1
                role_services:
                  type: array
                  items:
                    required: [role_id, service_ids]
                    properties:
                      role_id:
                        type: string
                        minLength: 1
                      service_ids:
                        type: array
                        items:
                          type: string
                          minLength: 1
                          maxLength: 15
                          pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
            persist_dirs:
              type: array
              items:
                type: string
                pattern: '^/.*[^/]$'
            capabilities:
              type: array
              items:
                type: string
                minLength: 1
            systemdRequired:
              type: boolean
